version: '2'

services:
  web:
    build:
      context: ./docker/
      dockerfile: web.docker
    volumes:
      - ./:/var/www:cached
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./docker/
      dockerfile: app.docker
    volumes:
      - ./:/var/www:cached
    links:
      - db
      - redis
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
  db:
    image: mysql:5.7
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql:cached
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "33061:3306"

  redis:
    build: ./docker/redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data:cached
    ports:
      - "16379:6379"

